/* EVENTS */
export const GET_SHIFTS = "GET_SHIFTS"
export const GET_SHIFTS_SUCCESS = "GET_SHIFTS_SUCCESS"
export const GET_SHIFTS_FAIL = "GET_SHIFTS_FAIL"

export const ADD_NEW_SHIFT = "ADD_NEW_SHIFT"
export const ADD_SHIFT_SUCCESS = "ADD_SHIFT_SUCCESS"
export const ADD_SHIFT_FAIL = "ADD_SHIFT_FAIL"

export const UPDATE_SHIFT = "UPDATE_SHIFT"
export const UPDATE_SHIFT_SUCCESS = "UPDATE_SHIFT_SUCCESS"
export const UPDATE_SHIFT_FAIL = "UPDATE_SHIFT_FAIL"

export const DELETE_SHIFT = "DELETE_SHIFT"
export const DELETE_SHIFT_SUCCESS = "DELETE_SHIFT_SUCCESS"
export const DELETE_SHIFT_FAIL = "DELETE_SHIFT_FAIL"

export const GET_PROJECT_TASKS = "GET_PROJECT_TASKS"
export const GET_PROJECT_TASKS_SUCCESS = "GET_PROJECT_TASKS_SUCCESS"
export const GET_PROJECT_TASKS_FAIL = "GET_PROJECT_TASKS_FAIL"
