/* EVENTS */
export const GET_SHIFTS = "GET_EVENTS"
export const GET_SHIFTS_SUCCESS = "GET_EVENTS_SUCCESS"
export const GET_SHIFTS_FAIL = "GET_EVENTS_FAIL"

export const ADD_NEW_SHIFT = "ADD_NEW_EVENT"
export const ADD_SHIFT_SUCCESS = "ADD_EVENT_SUCCESS"
export const ADD_SHIFT_FAIL = "ADD_EVENT_FAIL"

export const UPDATE_SHIFT = "UPDATE_EVENT"
export const UPDATE_SHIFT_SUCCESS = "UPDATE_EVENT_SUCCESS"
export const UPDATE_SHIFT_FAIL = "UPDATE_EVENT_FAIL"

export const DELETE_SHIFT = "DELETE_EVENT"
export const DELETE_SHIFT_SUCCESS = "DELETE_EVENT_SUCCESS"
export const DELETE_SHIFT_FAIL = "DELETE_EVENT_FAIL"

export const GET_PROJECT_TASKS = "GET_PROJECT_TASKS"
export const GET_PROJECT_TASKS_SUCCESS = "GET_PROJECT_TASKS_SUCCESS"
export const GET_PROJECT_TASKS_FAIL = "GET_PROJECT_TASKS_FAIL"
