/* TASKS */
export const GET_TASKS = "GET_TASKS"
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS"
export const GET_TASKS_FAIL = "GET_TASKS_FAIL"

export const DELETE_TASK = "DELETE_TASK"
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS"
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL"

export const ADD_TASK = "ADD_TASK"
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS"
export const ADD_TASK_FAIL = "ADD_TASK_FAIL"

export const UPDATE_TASK = "UPDATE_TASK"
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS"
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL"
export const CHANGE_SECTION = "CHANGE_SECTION";
export const CHANGE_SECTION_SUCCESS = "CHANGE_SECTION_SUCCESS";
export const CHANGE_SECTION_FAIL = "CHANGE_SECTION_FAIL";
export const ADD_SECTION = "ADD_SECTION";
export const ADD_SECTION_SUCCESS = "ADD_SECTION_SUCCESS";
export const ADD_SECTION_FAIL = "ADD_SECTION_FAIL";
export const DELETE_SECTION = "DELETE_SECTION";
export const DELETE_SECTION_SUCCESS = "DELETE_SECTION_SUCCESS";
export const DELETE_SECTION_FAIL = "DELETE_SECTION_FAIL";
export const UPDATE_SECTION = "UPDATE_SECTION";
export const UPDATE_SECTION_SUCCESS = "UPDATE_SECTION_SUCCESS";
export const UPDATE_SECTION_FAIL = "UPDATE_SECTION_FAIL";
